name: playground
on:
  push:
    branches:
    - playground
    - main

    paths:
    - 'playground/**'

jobs:

  container-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: build & push image
      run: |
        tag=$( awk -F'"' '/__version__/ {print $2}' src/cwl2ogc/__about__.py )
        IMAGE_ID=ghcr.io/eoap/cwl2ogc/playground
        docker build playground --file playground/Dockerfile --tag ${IMAGE_ID}${tag}
        docker push ${IMAGE_ID}${tag}